stark:
  executor:
    core: 4
    max: 8
    queue: 1000

spring:
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:postgresql://localhost:5433/benchdb
    username: benchuser
    password: benchpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.format_sql: true

server:
  port: 8080
